/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-06-21 01:14:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShimBeeSeo/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850415545L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShimBeeSeo/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bootstrap Example</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Web Fonts -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Icon Font Stylesheet -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/animate/animate.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t//$(\".page\").\r\n");
      out.write("\t\tpagingSetting();\r\n");
      out.write("\t\t$(\"#queWrap\").css(\"display\",\"\");\r\n");
      out.write("\t\t$(document).on('change', 'input', function(){\r\n");
      out.write("\t\t\tselectCheck();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction pagingSetting() {\r\n");
      out.write("\t\tvar totalQuePage = $(\".que\").length;\r\n");
      out.write("\t\tvar curPageId = $(\".curQue\").attr(\"id\");\r\n");
      out.write("\t\tvar curPage = curPageId.substring(curPageId.indexOf(\"que\")+3);\r\n");
      out.write("\t\t$(\".page\").text(curPage + \"/\" + totalQuePage);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* function goQuestion() {\r\n");
      out.write("\t\timgWrapClass = $(\"#imgWrap\").attr(\"class\");\r\n");
      out.write("\t\tif (imgWrapClass == \"on\") {\r\n");
      out.write("\t\t\t$(\"#imgWrap\").attr(\"class\", \"\");\r\n");
      out.write("\t\t\t$(\"#imgWrap\").css(\"right\", \"120%\");\r\n");
      out.write("\t\t\t$(\"#queWrap\").css(\"left\", \"\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} */\r\n");
      out.write("\r\n");
      out.write("\tfunction prevQue() {\r\n");
      out.write("\t\tvar curQue = $(\".curQue\");//현재 화면에 떠있는 질문 div태그의 id\r\n");
      out.write("\t\tvar prevQue = $(\".curQue\").prev();//현재 질문의 다음질문 div태그의 id\r\n");
      out.write("\t\t//$('.prevBtn').css(\"display\", \"\");\r\n");
      out.write("\t\tcurQue.attr(\"class\", \"que\");\r\n");
      out.write("\t\tcurQue.css(\"display\", \"none\");\r\n");
      out.write("\t\tprevQue.attr(\"class\", \"curQue que\");\r\n");
      out.write("\t\tprevQue.css(\"display\", \"\");\r\n");
      out.write("\t\tprevBtnShowing();\r\n");
      out.write("\t\tnextBtnShowing();\r\n");
      out.write("\t\tpagingSetting();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction nextQue() {\r\n");
      out.write("\t\tvar curQue = $(\".curQue\");//현재 화면에 떠있는 질문 div태그의 id\r\n");
      out.write("\t\tvar nextQue = $(\".curQue\").next();//현재 질문의 다음질문 div태그의 id\r\n");
      out.write("\t\t//$('.prevBtn').css(\"display\", \"\");//.css(\"display\",\"\")와 같이 빈란으로 속성을 적용하는 경우 이전 상태로 복원하는 것임(이전 상태에 아무것도 하지않은 상태면 css자체에서나 브라우저에서 자체적으로 지정하는 css 기본값으로 적용될 수도있음)\r\n");
      out.write("\t\tcurQue.attr(\"class\", \"que\");//요소에 class 속성 값으로 que를 대입한다 = 값이 que인 class 속성을 추가한다.\r\n");
      out.write("\t\tcurQue.css(\"display\", \"none\");\r\n");
      out.write("\t\tnextQue.attr(\"class\", \"curQue que\");\r\n");
      out.write("\t\tnextQue.css(\"display\", \"\");\r\n");
      out.write("\t\tprevBtnShowing();\r\n");
      out.write("\t\tnextBtnShowing();\r\n");
      out.write("\t\tpagingSetting();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction prevBtnShowing() {\r\n");
      out.write("\t\tcurId = $(\".curQue\").attr(\"id\");\r\n");
      out.write("\t\tif (curId == \"que1\") {//첫번째 질문인경우 이전버튼 숨김처리\r\n");
      out.write("\t\t\t$('.prevBtn').css(\"display\", \"none\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('.prevBtn').css(\"display\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction nextBtnShowing() {\r\n");
      out.write("\t\tcurId = $(\".curQue\").attr(\"id\");\r\n");
      out.write("\t\tlastId = $(\".que\").last().attr(\"id\");//선택한 div태그의 형제div 중 마지막div태그의 id(대신 모든 형제태그가 같은 class 값을 가져야 함)\r\n");
      out.write("\t\tif (curId == lastId) {//첫번째 질문인경우 다음버튼 숨김처리\r\n");
      out.write("\t\t\t$('.nextBtn').css(\"display\", \"none\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('.nextBtn').css(\"display\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* function checkboxArr() {\r\n");
      out.write("\t\tvar valueArr = [];\t\t// 배열 초기화\r\n");
      out.write("\t\t$(\"input[class=btn-check]:checked\").each(function(){\r\n");
      out.write("\t\t\tvar chk = $(this).val();\r\n");
      out.write("\t\t\tvalueArr.push(chk);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ScoreList.do',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\tdata : { \"valueArr\" : valueArr}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 미리보기 이미지 조정값 -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".que{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write(".wrapper .upload-btn input[type=file] {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-xxl bg-white p-0\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- 상자생성하고 사진넣어보기 -->\r\n");
      out.write("\t\t<section id=\"projects\" class=\"about-section text-center\">\r\n");
      out.write("\t\t\t<div style=\"margin-top: 0;\" class=\"testView\">\r\n");
      out.write("\t\t\t\t<h1><strong>집</strong></h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"uploadPhoto\">\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"POST\" enctype=\"multipart/form-data\" id=\"form_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"flex-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p id=\"fileInfo\">아래 버튼을 눌러 사진을 업로드 해주세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"position: relative;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/fileUpload.png\" class=\"image-box\" style=\"min-width:350px\"; height=\"350px\"; />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"file\" class=\"upload-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"file\" name=\"file\" type=\"file\" accept=\"image/*\" style=\"display: none;\" onchange=\"changeFile()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 미리보기 이후 파일 업로드하기 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- if문 써야함 대기중 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p id=\"submitInfo\" style=\"margin-top:3vw; display: none;\">제출 버튼을 눌러 AI에게 사진을 보내주세요!!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"submitPicture\"onclick=\"uploadFunction();\" class=\"form-control btn btn-primary\" style=\"width: 150px; display:none; color: white; background-color:#F86C85\">AI에게 사진제출</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--미리보기 테스트 끝 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div style=\"margin: 0; display:none;\" id=\"question\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"section-title-wrap mb-4\" style=\"margin-top:4vw;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"section-title text-center\">사진 상세 질문</h1>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- <form name=\"inputImg\" method=\"POST\"> -->\r\n");
      out.write("\t\t\t\t<div style=\"display: flex; width: 100%; margin-top: 6vw;\" class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%; display: block; margin: 0 auto\" class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"checkboxes\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ScoreList.do\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%;height:auto; min-height:700px;position:relative;overflow:hidden;background-image:url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/sk(1).png'); background-repeat : no-repeat; background-size : 100% 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"queWrap\" class=\"\" style=\"width:100%;height:auto; padding:55px 40px 90px 18px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"que1\" class=\"que curQue\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\" margin-top:2vw; font-size: 20pt; color:black\">1. 그림의 전체적인 분위기는 어떤가요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"mood\" value=\"1\" id=\"mood1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\"margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"mood1\">보통</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"mood\" value=\"2\" id=\"mood2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\"margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"mood2\">조금 부정적</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"mood\" value=\"3\" id=\"mood3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\"margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"mood3\">완전 부정적</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">2. 종이의 전체 면적에서 집이 얼마나 차지하나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"size\" value=\"4\" id=\"size1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\"margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"size1\">보통(중앙에서 2/3 정도 차지)</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"size\" value=\"5\" id=\"size2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"size2\">지나치게 큼</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"size\" value=\"6\" id=\"size3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"size3\">지나치게 작음</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"size\" value=\"7\" id=\"size4\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"size4\">파손 됨(절단된 집)</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">3. 그림에서 집은 어느쪽에 위치해 있나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"position\" value=\"8\" id=\"position1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"position1\">좌측</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"position\" value=\"9\" id=\"position2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"position2\">우측</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"position\" value=\"10\" id=\"position3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\"margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"position3\">하단</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"position\" value=\"11\" id=\"position4\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"position4\">해당되는 특징이 없음</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"que2\" class=\"que\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">4. 어떤 시점으로 그림이 그려졌나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"sight\" value=\"12\" id=\"sight1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"sight1\">윗면(위에서 내려다보는)</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"sight\" value=\"13\" id=\"sight2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"sight2\">아랫면(아래에서 올려다보는)</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"sight\" value=\"14\" id=\"sight3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"sight3\">해당되는 특징이 없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">5. 지붕은 어떻게 묘사되었나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"roof\" value=\"15\" id=\"roof1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"roof1\">과도하게 큼, 강한선 묘사</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"roof\" value=\"16\" id=\"roof2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"roof2\">과도한 무늬</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"roof\" value=\"17\" id=\"roof3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"roof3\">뾰족함 또는 세모 모양</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"roof\" value=\"18\" id=\"roof4\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"roof4\">지붕을 덧칠 또는 뭉개는 채색</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"roof\" value=\"19\" id=\"roof5\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"roof5\">해당되는 특징이 없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"que3\" class=\"que\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">6. 집을 구성하는 벽의 모습은 어떤가요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"wall\" value=\"20\" id=\"wall1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"wall1\">허술한 벽</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"wall\" value=\"21\" id=\"wall2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"wall2\">지나치게 견고한 벽돌이나 벽면</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"wall\" value=\"22\" id=\"wall3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"wall3\">해당되는 특징이 없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">7. 현관문의 크기와 모양은 어떻게 묘사되었나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"door\" value=\"23\" id=\"door1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"door1\">과하게 큼</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"door\" value=\"24\" id=\"door2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"door2\">과하게 작음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"door\" value=\"25\" id=\"door3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"door3\">집의 측면에 위치</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"door\" value=\"26\" id=\"door4\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"door4\">덧칠된 또는 잠금장치가 있는 현관문</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"door\" value=\"27\" id=\"door5\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"door5\">없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"door\" value=\"28\" id=\"door6\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"door6\">해당되는 특징이 없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"que4\" class=\"que\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">8. 창문은 어떤 특징이 있나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"window\" value=\"29\" id=\"window1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"window1\">없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"window\" value=\"30\" id=\"window2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"window2\">3개 이상</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"window\" value=\"31\" id=\"window3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"window3\">커튼으로 가려짐</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"window\" value=\"32\" id=\"window4\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"window4\">2층 이상의 지붕위에만 있음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"window\" value=\"50\" id=\"window5\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"window5\">해당되는 특징이 없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">9. 굴뚝의 모습에 특징이 있나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"chimney\" value=\"33\" id=\"chimney1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"chimney1\">없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"chimney\" value=\"34\" id=\"chimney2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"chimney2\">연기가 없는 굴뚝</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"btn-check\" name=\"chimney\" value=\"35\" id=\"chimney3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"chimney3\">연기나는 굴뚝</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\"aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">10. 그림에 태양이 묘사되어 있나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"sun\" value=\"36\" id=\"sun1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"sun1\">반만 나온 태양</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"sun\" value=\"37\" id=\"sun2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"sun2\">무채색 태양</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"sun\" value=\"38\" id=\"sun3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"sun3\">없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"sun\" value=\"39\" id=\"sun4\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"sun4\">해당되는 특징이 없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"que5\" class=\"que\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical radio toggle button group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"margin-top:2vw; font-size: 20pt; color:black\">11. 그림에 묘사된 다른 모습들이 있나요?</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"40\" id=\"etc1\" autocomplete=\"off\" onclick=\"selectCheck()\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-top: 1.9vw; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc1\">산속 또는 숲속 집</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"41\" id=\"etc2\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc2\">울타리가 있거나 울타리같은 지면</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"42\" id=\"etc3\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc3\">연못, 우물, 비 표현</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"43\" id=\"etc4\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc4\">벽 등을 통해 투시되는 집 내부</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"44\" id=\"etc5\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc5\">의인화된 집</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"45\" id=\"etc6\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" font-size:13px; margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc6\">음영,그림자표현 또는지웠다그리기를 반복한흔적</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"46\" id=\"etc7\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc7\">평면도형태의 집</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"47\" id=\"etc8\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc8\">덧칠된 채색</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"48\" id=\"etc9\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc9\">넓고 자세한 선으로 강조된 지면선</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"btn-check\" name=\"etc\" value=\"49\" id=\"etc10\" autocomplete=\"off\" onclick=\"selectCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\" margin-bottom: 1.9vw; border-radius: .6rem;\" class=\"btn btn-outline-danger\" for=\"etc10\">해당되는 특징 없음</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pagingWraper\" style=\"position:absolute;left:31%;bottom:0;padding-bottom:60px\">\r\n");
      out.write("                              \t\t\t<button type=\"button\" class=\"prevBtn\" onclick=\"prevQue();\">이전</button>\r\n");
      out.write("                              \t\t\t<span class=\"page\"></span>\r\n");
      out.write("                              \t\t\t<button type=\"button\" class=\"nextBtn\" onclick=\"nextQue();\">다음</button>\r\n");
      out.write("                           \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- get : 도메인쪽에 내가 입력한 것이 붙어서 서버쪽으로 가는 것 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- post: 정보은닉이 되어 서버쪽으로 가는 것 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- checkbox는 name이 같아야함 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 여러개 선택할 수 있음 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"result_direction\" id=\"result_direction\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"btn btn-info\" style=\"background-color: #F86C85; border-color: #FE5D37; color: white; margin-right:30px;\" id=\"submitSend\" type=\"submit\" disabled='disabled' value=\"모든 질문에 답변해주세요\" onclick=\"notification()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input class=\"btn btn-info\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #FE5D37; border-color: #FE5D37; color: white\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"picSend\" type=\"button\" value=\"button\" onclick=\"checkboxArr()\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"resultView\">\r\n");
      out.write("\t\t\t\t\t<h3 id=\"resultTxt\"></h3>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("          \t<div id=\"result\"></div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScript Libraries -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/wow/wow.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/easing/easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template Javascript -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/* event.preventDefault(); */\r\n");
      out.write("\r\n");
      out.write("\t\t/* let url = 'http://192.168.56.1:9000/photo'; */\r\n");
      out.write("\r\n");
      out.write("\t\t/* \t \tconst response = fetch('http://192.168.56.1:9000/photo', {\r\n");
      out.write("\t\t method: 'POST',\r\n");
      out.write("\t\t body: formData\r\n");
      out.write("\t\t }); */\r\n");
      out.write("\r\n");
      out.write("\t\t/* const formData = new FormData(); */\r\n");
      out.write("\r\n");
      out.write("/* =========================이미지 모델에게 확인 요청 ================================= */\r\n");
      out.write("\t\tfunction uploadFunction() {\r\n");
      out.write("\t\t\t$('#submitPicture').prop('disabled',true);\r\n");
      out.write("\t\t\t$('#submitPicture').text('AI가 사진을 분석중입니다.');\r\n");
      out.write("\t\t\t// 임의 test, id값 쿼리스트링으로 보내기\r\n");
      out.write("\t\t\tvar id = 'samsam';\r\n");
      out.write("\t\t\tvar data = new FormData(form_img);\r\n");
      out.write("\t\t\tconsole.log(\"파일 업로드 요청\");\r\n");
      out.write("\t\t\tsaveImageBeforeUpload(data);\r\n");
      out.write("\t\t\t/* async : false -> 비동기 동기로 변경, 다만 값 받아오기 전에 페이지 이동해 버리면 값 못받고 넘어감!! 주의하자! */\r\n");
      out.write("\t\t\t// http://211.105.164.246:9000/test\r\n");
      out.write("\t\t\t$('#question').css('display','block')\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\tenctype : \"multipart/form-data\",\r\n");
      out.write("\t\t\t\turl : \"http://211.105.164.246:9000/h_photo/\" + 1,\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\ttimeout : 600000,\r\n");
      out.write("\t\t\t\tsuccess : function(items) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (res = !null) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"파일 업로드 성공\");\r\n");
      out.write("\t\t\t\t\t\t// res 출력은 true만 나옴.. 어케 받아오지..?\r\n");
      out.write("\t\t\t\t\t\tconsole.log(items['message']);\r\n");
      out.write("\t\t\t\t\t\t// 값 받아와서 히든태그에 집어 넣기!!\r\n");
      out.write("\t\t\t\t\t\t// null값 체크해서 페이지 이동 막아줘야 함\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar addInput = document.querySelector('#que1');\r\n");
      out.write("\t\t\t\t\t\taddInput.innerHTML += \"<input type='hidden' name='item' value='\"+items['message']+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// ChatGPT에 객체 탐지 결과 불러와서 질문 집어넣기\r\n");
      out.write("\t\t\t\t\t\tvar prompt = \"\";\r\n");
      out.write("\t\t\t\t\t\tvar cnt = 1;\r\n");
      out.write("\t\t\t\t\t\tvar inputText = items['message'];\r\n");
      out.write("\t\t\t\t\t\tvar keywordSplitYes = inputText.split(\";\")[0];\r\n");
      out.write("\t\t\t\t\t\tvar keywordSplitNo = inputText.split(\";\")[1];\r\n");
      out.write("\t\t\t\t\t\tvar keywordExist = keywordSplitYes.split(\",\");\r\n");
      out.write("\t\t\t\t\t\tvar keywordNull = keywordSplitNo.split(\",\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tconsole.log(keywordExist);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(keywordNull);\r\n");
      out.write("\t\t\t\t\t\tprompt += \"HTP검사중에 집그림 검사를 시작할거야 대상은 8세 미만의 아동이야\\n\";\r\n");
      out.write("\t\t\t\t\t\tfor(var i = 0 ; i < keywordExist.length; i++){\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'door'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\".문이 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'window'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\".창문이 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'wall'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\".벽이 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'chimney'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\".굴뚝이 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'roof'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\".지붕이 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'sun'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\".태양이 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'c_smoke'){\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\"굴뚝과 연기가 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'fence'){\r\n");
      out.write("\t\t\t\t\t\t\tprompt+=cnt+\"울타리가 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(keywordExist[i]== 'tree'){\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\"나무가 존재함 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i = 0 ; i < keywordNull.length; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'door'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\".문이 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'window'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\".창문이 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'wall'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\".벽이 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'chimney'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\".굴뚝이 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'roof'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\".지붕이 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'sun'){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\".태양이 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'c_smoke'){\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\"굴뚝과 연기가 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'fence'){\r\n");
      out.write("\t\t\t\t\t\t\t\tprompt+=cnt+\"울타리가 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(keywordNull[i]== 'tree'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tprompt+=cnt+\"나무가 없음 \\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tprompt+=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\tprompt += \"위 검사 결과를 바탕으로 아이의 양육방식에 대하여 부모님의 관점으로 5가지 말해줘\";\r\n");
      out.write("\t\t\t\t\t\tconsole.log(prompt);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t/* url : \"http://alrrla.pythonanywhere.com/chatbot\", */\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"http://121.147.0.189:9900/chatbot\",\r\n");
      out.write("\t\t\t\t\t\t\t\tType : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\t\tasync : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : {\"message\" : prompt},\r\n");
      out.write("\t\t\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\t\t\tcontentType: 'application/json; charset=utf-8',\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function (chatbot_response){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(chatbot_response['response']);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#result_direction').val(chatbot_response['response']);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#submitPicture').prop('disabled',false);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#submitPicture').text('ChatGPT 답변완료!');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcompleteCheck();\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function (){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"flask에서 아무고토 못받음\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"파일 업로드 실패\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"파일 업로드 에러\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t}); };\r\n");
      out.write("\t\t//http://211.105.164.246:9000/test\r\n");
      out.write("\t\tfunction saveImageBeforeUpload(data){\r\n");
      out.write("\t\t\tvar csrfHeaderName = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\tvar csrfTokenValue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\tenctype : 'multipart/form-data',\r\n");
      out.write("\t\t\t\turl : \"saveImage.do\",\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\t/* async : false, */\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\tbeforeSend : function(xhr){\r\n");
      out.write("\t    \t\t\t xhr.setRequestHeader(csrfHeaderName, csrfTokenValue);\r\n");
      out.write("\t    \t\t },\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tif(data == \"success\"){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tvar addInput = document.querySelector('#que1');\r\n");
      out.write("\t\t\t\t\t\taddInput.innerHTML += \"<input type='hidden' name='photo' value=\"+data+\">\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"파일 저장 에러\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 이미지 미리보기 처리 -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tconst fileDOM = document.querySelector('#file');\r\n");
      out.write("\tconst upload = document.querySelector('.image-box')\r\n");
      out.write("\tconst previews = document.querySelectorAll('.image-box');\r\n");
      out.write("\t\r\n");
      out.write("\tupload.addEventListener('click', () => fileDOM.click());\r\n");
      out.write("\t\r\n");
      out.write("\tfileDOM.addEventListener('change', () => {\r\n");
      out.write("\t  const reader = new FileReader();\r\n");
      out.write("\t  reader.onload = ({ target }) => {\r\n");
      out.write("\t    previews[0].src = target.result;\r\n");
      out.write("\t  };\r\n");
      out.write("\t  reader.readAsDataURL(fileDOM.files[0]);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction changeFile(){\r\n");
      out.write("\t\tconsole.log('changeFile 잘 됨');\r\n");
      out.write("\t\tvar file = $('#file');\r\n");
      out.write("\t\tconsole.log(file);\r\n");
      out.write("\t\tif(file != null){\r\n");
      out.write("\t\t\t$('#fileInfo').css('display', 'none');\r\n");
      out.write("\t\t\t$('#submitInfo').css('display','inline-block');\r\n");
      out.write("\t\t\t$('#submitPicture').css('display','inline-block');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#submitPicture').css('display','none');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tfunction selectCheck(){\r\n");
      out.write("\t\tvar mood = $('input[name=mood]').is(\":checked\");\r\n");
      out.write("\t\tvar size = $('input[name=size]').is(\":checked\");\r\n");
      out.write("\t\tvar position = $('input[name=position]').is(\":checked\");\r\n");
      out.write("\t\tvar sight = $('input[name=sight]').is(\":checked\");\r\n");
      out.write("\t\tvar roof = $('input[name=roof]').is(\":checked\");\r\n");
      out.write("\t\tvar wall = $('input[name=wall]').is(\":checked\");\r\n");
      out.write("\t\tvar door = $('input[name=door]').is(\":checked\");\r\n");
      out.write("\t\tvar window = $('input[name=window]').is(\":checked\");\r\n");
      out.write("\t\tvar chimney = $('input[name=chimney]').is(\":checked\");\r\n");
      out.write("\t\tvar sun = $('input[name=sun]').is(\":checked\");\r\n");
      out.write("\t\tvar etc = $('input[name=etc]').is(\":checked\");\r\n");
      out.write("\r\n");
      out.write("\t\tif(mood == true && size == true && position == true && sight == true && roof == true && wall == true && door == true && window == true && chimney == true && sun == true && etc == true){\r\n");
      out.write("\t\t\tconsole.log(\"전부 체크됨\");\r\n");
      out.write("\t\t\t/* var checkPicture = $('#submitPicture').text();\r\n");
      out.write("\t\t\tif(checkPicture == '분석완료! 설문을 진행해주세요'){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$('#submitSend').attr(\"disabled\", false);\r\n");
      out.write("\t\t\t$('#submitSend').attr(\"value\",'제출하기');\r\n");
      out.write("\t\t\t} */\r\n");
      out.write("\t\t\tif($('#submitPicture').text() == 'ChatGPT 답변완료!') {\r\n");
      out.write("\t\t\t\tcompleteCheck;\r\n");
      out.write("\t\t\t\t$('#submitSend').attr(\"disabled\", false);\r\n");
      out.write("\t\t\t\t$('#submitSend').attr(\"value\",'제출하기');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#submitSend').attr(\"disabled\", true);\r\n");
      out.write("\t\t\t\t$('#submitSend').attr(\"value\",'ChatGPT의 답변을 기다리고 있습니다.');\r\n");
      out.write("\t\t\t\tcompleteCheck;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tconsole.log(\"체크 누락됨\")\r\n");
      out.write("\t\t\t$('#submitSend').attr(\"disabled\", true);\r\n");
      out.write("\t\t\t$('#submitSend').attr(\"value\",'답변을 완료해주세요.');\r\n");
      out.write("\t\t\tcompleteCheck;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction completeCheck() {\r\n");
      out.write("\t\tvar checkPicture = $('#submitPicture').text();\r\n");
      out.write("\t\tif(checkPicture == 'ChatGPT 답변완료!' && selectCheck()){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$('#submitSend').attr(\"disabled\", false);\r\n");
      out.write("\t\t$('#submitSend').attr(\"value\",'제출하기');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 카카오톡 나에게 보내기 Flask요청 -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction notification(){\r\n");
      out.write("\t\tvar date = new Date();\r\n");
      out.write("\t    var year = date.getFullYear();\r\n");
      out.write("\t    var month = (\"0\" + (1 + date.getMonth())).slice(-2);\r\n");
      out.write("\t    var day = (\"0\" + date.getDate()).slice(-2);\r\n");
      out.write("\t    var today= year + \"-\" + month + \"-\" + day;\r\n");
      out.write("\t    console.log(today);\r\n");
      out.write("\t\tvar accessToken = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accessToken}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t    console.log(accessToken);\r\n");
      out.write("\r\n");
      out.write("\t\tvar name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t    console.log(name);\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"http://alrrla.pythonanywhere.com/kakao\",\r\n");
      out.write("\t\t\tType : \"get\",\r\n");
      out.write("\t\t\tdata : {\"accessToken\" : accessToken,\r\n");
      out.write("\t\t\t\t\t\"name\" : name,\r\n");
      out.write("\t\t\t\t\t\"today\" : today},\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tcontentType: 'application/json; charset=utf-8',\r\n");
      out.write("\t\t\tsuccess : function(message){\r\n");
      out.write("\t\t\t\tconsole.log(message);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function (){\r\n");
      out.write("\t\t\t\tconsole.log(\"카카오톡 알림 실패 ㅠㅠ\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main/test2.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/main/test2.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/test2.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
